### ISSUE TITLE
select_block函数的参数语义问题

### ISSUE THREAD

**Issue by flynnoct** [AItransCompetition/simple_emulator#4]
关于其参数block_queue，从参数名和注释中看，其是一个Block对象的list，但是

1. readme中对block_queue中元素的描述同时使用了block和packet两个词汇。
2. 从readme和simple_emulator本身的实现来看，Block对象并没有block_info这个属性，但是示例解决方案中却访问了这个属性

https://github.com/AItransCompetition/simple_emulator/blob/dbbf151e102ee8951b6a99db23b1d8e2b75d90e7/player/block_selection.py#L15-L17

所以我想请问一下block_queue是一个Block对象的list还是Packet对象的list，亦或是其他？

**Comment by Azson** [comment]
You can get the input of block_queue from the [block_queue](https://github.com/AItransCompetition/simple_emulator#table--block_queue).
The type of block_queue is a dict in python. And every element of it is a dict which contain the information of it's block and packet that it belongs to.
System will get block from application and send packet splited from a special block.
But it may be good to do schedule if we know the block information which the packet belongs to, like the priority or deadline.
For this reason, we provided such information in Block Scheduler.
Lastly, you should realize the line 15 that you quoted is handling the object from block_queue.

**Comment by flynnoct** [comment]
Thank you for your reply!
Actually, when I use `type(block_queue)` in solution, I get `<class 'list'>`  instead of `<class 'dict'>`.  And about my previous question, I confirmed that the elements of the list are Packet objects by using `isinstance(block_queue[i], Packet)`. These confuse me.

You said: 
> System will get block from application and send packet splited from a special 

Can I understand it this way: the `block_selection` function receives a list `block_queue` includes a bunch of packets which belong to different blocks. Since the index returned at the end of the function is the index of the `block_queue` list, the function actually return **the index of the packet that needs to be sent in current.** This function **schedules on packet level** with the information of the block.

**Comment by Azson** [comment]
Sorry. I confirmed that the type of block_queue[i] is Packet in [here](https://github.com/AItransCompetition/simple_emulator/blob/dbbf151e102ee8951b6a99db23b1d8e2b75d90e7/objects/application.py#L154).
And your understand to block schedule is right!

**Comment by flynnoct** [comment]
Thanks, your reply helps a lot.
Have a nice day :)
